# shellcheck shell=sh
# lib/setup.sh — populate a chroot's internals so networking, name resolution,
# and a sane environment work the moment you enter.

# write /etc/resolv.conf from detected DNS servers
setup_resolv() {
	_rfs=$1
	_rc="$_rfs/etc/resolv.conf"
	mkdir -p "$_rfs/etc" 2>/dev/null
	# resolv.conf is sometimes a dangling symlink (systemd-resolved); replace it
	[ -L "$_rc" ] && rm -f "$_rc" 2>/dev/null
	{
		printf '# generated by achroot\n'
		detect_dns | while read -r _ip; do
			[ -n "$_ip" ] && printf 'nameserver %s\n' "$_ip"
		done
		printf 'options ndots:0\n'
	} > "$_rc" 2>/dev/null || log_warn "could not write resolv.conf"
}

# minimal /etc/hosts + hostname
setup_hosts() {
	_rfs=$1; _hn=${ACH_HOSTNAME:-localhost}
	mkdir -p "$_rfs/etc" 2>/dev/null
	printf '%s\n' "$_hn" > "$_rfs/etc/hostname" 2>/dev/null || true
	if [ ! -s "$_rfs/etc/hosts" ] || ! grep -q "$_hn" "$_rfs/etc/hosts" 2>/dev/null; then
		{
			printf '127.0.0.1\tlocalhost %s\n' "$_hn"
			printf '::1\t\tlocalhost ip6-localhost ip6-loopback\n'
		} > "$_rfs/etc/hosts" 2>/dev/null || true
	fi
}

# /etc/mtab -> /proc/mounts so `df`, `mount` (no args), etc. behave
setup_mtab() {
	_rfs=$1
	if [ ! -e "$_rfs/etc/mtab" ]; then
		ln -sf /proc/mounts "$_rfs/etc/mtab" 2>/dev/null || true
	fi
}

# drop a friendly login banner / prompt + PATH hardening
setup_profile() {
	_rfs=$1
	mkdir -p "$_rfs/etc/profile.d" 2>/dev/null || return 0
	cat > "$_rfs/etc/profile.d/00-achroot.sh" 2>/dev/null <<'EOF'
# managed by achroot — safe to edit, regenerated on `start`
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
[ -z "$LANG" ] && export LANG=C.UTF-8
# only set a fancy prompt for interactive shells
case "$-" in *i*)
	if [ -n "$BASH_VERSION" ]; then
		PS1='\[\e[1;32m\](chroot)\[\e[0m\] \[\e[1;34m\]\w\[\e[0m\] # '
	else
		PS1='(chroot) # '
	fi
	;;
esac
EOF
	return 0
}

# run user hook scripts placed at <chroot_dir>/hooks/onstart.d/*
run_start_hooks() {
	_name=$1; _rfs=$2
	_hd="$(chroot_dir "$_name")/hooks/onstart.d"
	[ -d "$_hd" ] || return 0
	for _h in "$_hd"/*; do
		[ -f "$_h" ] || continue
		log_info "hook: $(basename "$_h")"
		ACH_ROOTFS="$_rfs" ACH_NAME="$_name" sh "$_h" 2>&1 | sed 's/^/      /' >&2 || \
			log_warn "hook failed: $_h"
	done
}

# --- SELinux convenience ---------------------------------------------------

_selinux_saved=""

# temporarily set permissive if policy is enforcing (chroots frequently trip
# over denials). Honors ACH_MANAGE_SELINUX = ask|auto|off. Restores on stop.
selinux_relax_if_needed() {
	[ "${ACH_MANAGE_SELINUX:-ask}" = "off" ] && return 0
	have setenforce || return 0
	[ "$(selinux_status)" = "Enforcing" ] || return 0
	case "${ACH_MANAGE_SELINUX:-ask}" in
		auto) : ;;
		ask)
			confirm "SELinux is Enforcing; set Permissive while the chroot runs? (improves compatibility)" \
				|| { log_info "leaving SELinux Enforcing"; return 0; } ;;
	esac
	log_info "setting SELinux Permissive (was Enforcing)"
	run setenforce 0 2>/dev/null && _selinux_saved=1 || log_warn "setenforce 0 failed"
}

cmd_selinux() {
	case "${1:-status}" in
		status|"") printf 'SELinux: %s\n' "$(selinux_status)" ;;
		permissive|0) need_root; run setenforce 0 && log_ok "SELinux -> Permissive" ;;
		enforcing|1)  need_root; run setenforce 1 && log_ok "SELinux -> Enforcing" ;;
		*) die "usage: achroot selinux [status|permissive|enforcing]" ;;
	esac
}

# --- orchestration: bring a chroot fully up --------------------------------

start_chroot() {
	_name=$1
	require_chroot "$_name"
	need_root
	log_step "Starting '$_name'"
	selinux_relax_if_needed
	mount_chroot "$_name"
	_rfs=$(rootfs_path "$_name")
	setup_resolv "$_rfs"
	setup_hosts  "$_rfs"
	setup_mtab   "$_rfs"
	setup_profile "$_rfs"
	run_start_hooks "$_name" "$_rfs"
	meta_set "$_name" last_started "$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null || echo unknown)"
	log_ok "'$_name' is up. Enter it with:  achroot enter $_name"
}

cmd_start() { start_chroot "$1" ; }

cmd_stop() {
	_name=$1
	require_chroot "$_name"
	need_root
	log_step "Stopping '$_name'"
	# best-effort: kill processes whose root is inside this chroot
	_stop_chroot_procs "$_name"
	umount_chroot "$_name"
	log_ok "'$_name' stopped (filesystems unmounted)"
}

cmd_stopall() {
	need_root
	log_step "Stopping all chroots"
	if [ -d "$ACH_DISTROS" ]; then
		for _d in "$ACH_DISTROS"/*/; do
			[ -d "$_d" ] || continue
			_n=$(basename "$_d")
			is_started "$_n" && cmd_stop "$_n"
		done
	fi
	log_ok "done"
}

# kill processes still running inside the chroot before unmounting
_stop_chroot_procs() {
	_rfs=$(_realpath "$(rootfs_path "$1")")
	_killed=0
	for _p in /proc/[0-9]*; do
		_root=$(readlink "$_p/root" 2>/dev/null) || continue
		case "$_root" in
			"$_rfs"|"$_rfs"/*)
				_pid=$(basename "$_p")
				[ "$_pid" = "$$" ] && continue
				kill -TERM "$_pid" 2>/dev/null && _killed=$((_killed+1)) ;;
		esac
	done
	[ "$_killed" -gt 0 ] && { log_info "signalled $_killed process(es) inside the chroot"; sleep 1; }
	return 0
}
